### ISSUE TITLE
chore(packaging,deps): enable "dynamic" package version from git tags

### ISSUE THREAD

**Issue by danceratopz** [ethereum/execution-specs#1451]
Consider using [setuptools-scm](https://github.com/pypa/setuptools-scm) and setting `dynamic = ["version"]`, something along the lines of:

```toml
[project]
dynamic = ["version"]  # Let the build backend determine the version

[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
```
